#
# Makefile for Maemo Aegis security framework
#

obj-$(CONFIG_SECURITY_AEGIS_VALIDATOR)	+= validator/
obj-$(CONFIG_SECURITY_AEGIS_RESTOK)	+= restok/
obj-$(CONFIG_SECURITY_AEGIS_CREDS)	+= creds/
obj-$(CONFIG_SECURITY_AEGIS_CREDP)	+= credp/
