#
# Makefile for HSI clients
#

obj-$(CONFIG_NOKIA_MODEM)	+= nokia-modem.o
obj-$(CONFIG_SSI_PROTOCOL)	+= ssi_protocol.o
obj-$(CONFIG_HSI_CHAR)		+= hsi_char.o
obj-$(CONFIG_HSI_CMT_SPEECH)	+= cmt_speech.o
